#!/bin/bash
# Test script to demonstrate manual playlist entry

echo "This demonstrates the manual playlist entry feature:"
echo ""
echo "When you run: python3 main.py"
echo ""
echo "And auto-fetch fails, you'll see:"
echo "  1. Press Enter to export Watch Later (default)"
echo "  2. Type 'manual' to enter playlist URLs manually"
echo ""
echo "If you choose 'manual', you can enter playlist URLs like:"
echo "  - https://www.youtube.com/playlist?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf"
echo "  - https://www.youtube.com/watch?v=abc123&list=PLxxx..."
echo ""
echo "Then give each playlist a custom name, and type 'done' when finished."
echo ""
echo "Example session:"
echo "  Enter playlist URL (or 'done'): https://www.youtube.com/playlist?list=PLrAXtmErZgOeiKm4sgNOknGvNjby9efdf"
echo "  Enter a name for this playlist: My Coding Tutorials"
echo "  ✅ Added: My Coding Tutorials"
echo ""
echo "  Enter playlist URL (or 'done'): https://www.youtube.com/playlist?list=PLxxxxxx"
echo "  Enter a name for this playlist: Music Playlist"
echo "  ✅ Added: Music Playlist"
echo ""
echo "  Enter playlist URL (or 'done'): done"
echo ""
echo "Then it will export both playlists to separate CSV files!"
